### ISSUE TITLE
Getting Error When trying to connect to https://api.corona-zahlen.org/germany

### ISSUE THREAD

**Issue by antonstech** [marlon360/rki-covid-api#122]
```
{"error":{"message":"An error occurred.","details":"Cannot read property 'replace' of undefined","stack":"TypeError:
Cannot read property 'replace' of undefined\n at rValue (/usr/src/app/src/data-requests/r-value.ts:42:38)\n at Object.
<anonymous> (/usr/src/app/src/data-requests/r-value.ts:52:19)\n at Generator.next (<anonymous>)\n at fulfilled
		(/usr/src/app/dist/data-requests/r-value.js:5:58)\n at runMicrotasks (<anonymous>)\n at
			processTicksAndRejections (internal/process/task_queues.js:97:5)"}}
```

**Comment by Sarcasmonaut** [comment]
Hey, I had a look at the issue and found that it's due to a parsing problem while trying to extract R-value data from the source csv.

The keys used to extract the required data contain Umlauts (ä):
```
const csvRvalueFields = ['Schätzer_7_Tage_R_Wert', 'Punktschätzer des 7-Tage-R Wertes']
```
However, unfortunately, the headers in the csv look like the following right now: 

> headers: Datum,Sch�tzer_Neuerkrankungen,UG_PI_Neuerkrankungen,OG_PI_Neuerkrankungen,Sch�tzer_Neuerkrankungen_ma4,UG_PI_Neuerkrankungen_ma4,OG_PI_Neuerkrankungen_ma4,Sch�tzer_Reproduktionszahl_R,UG_PI_Reproduktionszahl_R,OG_PI_Reproduktionszahl_R,Sch�tzer_7_Tage_R_Wert,UG_PI_7_Tage_R_Wert,OG_PI_7_Tage_R_Wert

**Comment by Rubber1Duck** [comment]
hmmm downloading the cvs with my windows maschine and oben as a text file looks like this 

![RKI3](https://user-images.githubusercontent.com/6493772/111215906-fc27ea00-85d3-11eb-9d91-68dabe291a84.png)

as you can see all Headers are right! 

Marlon maybe it is better to switch to the xlsx file ?? (if there is a problem with the code page)
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen.xlsx?__blob=publicationFile

i think parsing is easier!?

Maybe tomorrow all went well ..................

**Comment by Sarcasmonaut** [comment]
fetching it via ```https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen_csv.csv?__blob=publicationFile``` with postman does show the malformed headers as well, curiously only some of the umlauts are broken:
broken:
![image](https://user-images.githubusercontent.com/25012926/111217507-ea474680-85d5-11eb-90a2-1a33dfb7a11b.png)

correct:
![image](https://user-images.githubusercontent.com/25012926/111217544-f6330880-85d5-11eb-87a3-2cd62745afb0.png)

**Comment by Sarcasmonaut** [comment]
a bit of a hacky workaround could be to switch to [startsWith](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) and `endsWith` respectively, instead of the `===` comparison

**Comment by Rubber1Duck** [comment]
i think thats a "code page" problem, "Umlaute" are often a problem, but till now it works .................

**Comment by marlon360** [comment]
I will switch to the `xlsx` file as @Rubber1Duck suggested, thanks!

**Comment by marlon360** [comment]
Fixed with 7969b65c3c0e73a5618c551ca28c7c739e7d62bb

**Comment by Rubber1Duck** [comment]
unfortnatly still not working .......... ?!
![germany](https://user-images.githubusercontent.com/6493772/111371248-72daeb00-8699-11eb-80c3-96a76e729724.png)

**Comment by marlon360** [comment]
Feels like the RKI is changing the structure every hour...

**Comment by marlon360** [comment]
Fixed with 663f6c3ef501ac9d4dc876167001079877a61294
Deployed and online in 10 minutes.
