### ISSUE TITLE
Error for germany and districts

### ISSUE THREAD

**Issue by marcusraitner** [marlon360/rki-covid-api#276]
When calling 

`https://api.corona-zahlen.org/districts/` 

I get 

`{"error":{"message":"An error occurred.","details":"Request failed with status code 502","stack":"Error: Request failed with status code 502\n    at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:326:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:506:15)\n    at endReadableNT (_stream_readable.js:1241:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}}`

same for `https://api.corona-zahlen.org/germany`

**Comment by Unwies** [comment]
Same here, also for https://api.corona-zahlen.org/districts/02000 etc.

**Comment by wolfdave** [comment]
Again https://api.corona-zahlen.org/districts/14713/history/incidence/3 :( 

`{"error":{"message":"An error occurred.","details":"Request failed with status code 502","stack":"Error: Request failed with status code 502\n    at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:326:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:506:15)\n    at endReadableNT (_stream_readable.js:1241:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}}`

**Comment by Rubber1Duck** [comment]
I am on vacation at the moment, but that looks like a error on the proxy server that this api is using!
my own server is running well (just tested) witch is not using any proxy….
That’s needs to be fixed by marlon……..

**Comment by helmar74** [comment]
Same here, for Germany and Bavria.
Looking forward for the fix ;-)

Thank a lot in advance.

**Comment by kaolick** [comment]
Is there any workaround? I'm already getting bad reviews on my app.

Thanks in advance

**Comment by Rubber1Duck** [comment]
One possible fix is run your own server....Am 04.09.2021 17:01 schrieb kaolick ***@***.***>:
Is there any workaround? I'm already getting bad reviews on my app.
Thanks in advance

**Comment by SystemKeeper** [comment]
Not sure if related, but I see exceptions on my own server as well. Haven’t had time to debug though

**Comment by Rubber1Duck** [comment]
Thats the respond on my own server for /germany :
{"cases":3995188,"deaths":92325,"recovered":3763636,"weekIncidence":80.68,"casesPer100k":4805,"casesPerWeek":67089,"delta":{"cases":10835,"deaths":24,"recovered":6023},"r":{"value":1.13,"rValue4Days":{"value":1.13,"date":"2021-08-31T00:00:00.000Z"},"rValue7Days":{"value":1.08,"date":"2021-08-30T00:00:00.000Z"},"lastUpdate":"2021-09-04T02:15:42.000Z"},"meta":{"source":"Robert Koch-Institut","contact":"Marlon Lueckert (m.lueckert@me.com)","info":"https://github.com/marlon360/rki-covid-api","lastUpdate":"2021-09-03T22:00:00.000Z","lastCheckedForUpdate":"2021-09-04T16:17:22.617Z"}}

**Comment by HappyFr1tz** [comment]
@kaolick There is already a solution. Host the API on your own server. There are no problems there at the moment.

**Comment by DanielMensch** [comment]
@HappyFr1tz thats not a real „solution“ IMHO! Support by marlon is appreciated.

**Comment by marlon360** [comment]
The server uses a proxy server by @shinebar1001.
@shinebar1001 do you think there is a problem on your end?

**Comment by shinebar1001** [comment]
@marlon360 There has been a problem with my DNS-server, so that the host could not been resolved. Fixed!

**Comment by marlon360** [comment]
> @marlon360 There has been a problem with my DNS-server, so that the host could not been resolved. Fixed!

Thanks for the quick fix!

**Comment by HappyFr1tz** [comment]
> @HappyFr1tz thats not a real „solution“ IMHO! Support by marlon is appreciated.

If someone is concerned about ratings on an app, then hosting it on its own server is obviously a solution. In the meantime, it has been fixed here, but despite this, you should not make yourself completely dependent on one thing. @DanielMensch

**Comment by marcusraitner** [comment]
`https://api.corona-zahlen.org/germany` is still not working … `districts` is.

**Comment by shinebar1001** [comment]
The response for /germany seems fine?

`{"cases":4005641,"deaths":92346,"recovered":3768434,"weekIncidence":83.11102667979283,"casesPer100k":4817.075950581992,"casesPerWeek":69111,"delta":{"cases":10453,"deaths":21,"recovered":4798},"r":{"value":1.2,"rValue4Days":{"value":1.2,"date":"2021-09-01T00:00:00.000Z"},"rValue7Days":{"value":1.09,"date":"2021-08-31T00:00:00.000Z"},"lastUpdate":"2021-09-05T02:13:13.000Z"},"meta":{"source":"Robert Koch-Institut","contact":"Marlon Lueckert (m.lueckert@me.com)","info":"https://github.com/marlon360/rki-covid-api","lastUpdate":"2021-09-04T23:00:00.000Z","lastCheckedForUpdate":"2021-09-05T06:05:25.047Z"}}`

**Comment by marcusraitner** [comment]
Yes, you're right. My fault.
